package ServerInterfacePackage;


/**
* ServerInterfacePackage/ResourceException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Friday, January 3, 2025 3:40:24 PM CET
*/

public final class ResourceException extends org.omg.CORBA.UserException
{
  public String message = null;

  public ResourceException ()
  {
    super(ResourceExceptionHelper.id());
  } // ctor

  public ResourceException (String _message)
  {
    super(ResourceExceptionHelper.id());
    message = _message;
  } // ctor


  public ResourceException (String $reason, String _message)
  {
    super(ResourceExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ResourceException
