
/**
* ClientIDListInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Friday, January 3, 2025 3:40:24 PM CET
*/

public interface ClientIDListInterfaceOperations 
{
  void addClientID (String clientId);
  void removeClientID (String clientId);
  String[] getClientIDs ();
} // interface ClientIDListInterfaceOperations
