
/**
* ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Friday, January 3, 2025 3:40:24 PM CET
*/

public interface ServerInterfaceOperations 
{

  // Responder methods
  String addResource (String resourceID, String resourceName, int duration) throws ServerInterfacePackage.ResourceException;
  String removeResource (String resourceID, int duration) throws ServerInterfacePackage.ResourceException;
  String listResourceAvailability (String resourceName) throws ServerInterfacePackage.ResourceException;

  // Coordinator methods
  String requestResource (String coordinatorID, String resourceID, int duration) throws ServerInterfacePackage.ResourceException;
  String findResource (String coordinatorID, String resourceName) throws ServerInterfacePackage.ResourceException;
  String returnResource (String coordinatorID, String resourceID) throws ServerInterfacePackage.ResourceException;
  String swapResource (String coordinatorID, String oldResourceID, String oldResourceType, String newResourceID, String newResourceType) throws ServerInterfacePackage.ResourceException;
  void addToQueue (String clientId, String resourceId);
} // interface ServerInterfaceOperations
