
/**
* ClientIDListInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Friday, January 3, 2025 3:40:24 PM CET
*/

public abstract class ClientIDListInterfacePOA extends org.omg.PortableServer.Servant
 implements ClientIDListInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addClientID", new java.lang.Integer (0));
    _methods.put ("removeClientID", new java.lang.Integer (1));
    _methods.put ("getClientIDs", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientIDListInterface/addClientID
       {
         String clientId = in.read_string ();
         this.addClientID (clientId);
         out = $rh.createReply();
         break;
       }

       case 1:  // ClientIDListInterface/removeClientID
       {
         String clientId = in.read_string ();
         this.removeClientID (clientId);
         out = $rh.createReply();
         break;
       }

       case 2:  // ClientIDListInterface/getClientIDs
       {
         String $result[] = null;
         $result = this.getClientIDs ();
         out = $rh.createReply();
         StringSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientIDListInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientIDListInterface _this() 
  {
    return ClientIDListInterfaceHelper.narrow(
    super._this_object());
  }

  public ClientIDListInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ClientIDListInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ClientIDListInterfacePOA
