
/**
* ClientIDListInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Friday, January 3, 2025 3:40:24 PM CET
*/

public final class ClientIDListInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientIDListInterface value = null;

  public ClientIDListInterfaceHolder ()
  {
  }

  public ClientIDListInterfaceHolder (ClientIDListInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientIDListInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientIDListInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientIDListInterfaceHelper.type ();
  }

}
