interface ServerInterface {

        exception ResourceException {
            string message;  // Error message
        };
        // Responder methods
        string addResource(in string resourceID, in string resourceName, in long duration) raises(ResourceException);
        string removeResource(in string resourceID, in long duration) raises(ResourceException);
        string listResourceAvailability(in string resourceName) raises(ResourceException);

        // Coordinator methods
        string requestResource(in string coordinatorID, in string resourceID, in long duration) raises(ResourceException);
        string findResource(in string coordinatorID, in string resourceName) raises(ResourceException);
        string returnResource(in string coordinatorID, in string resourceID) raises(ResourceException);
        string swapResource(in string coordinatorID, in string oldResourceID, in string oldResourceType, in string newResourceID,
        in string newResourceType) raises(ResourceException);
        void addToQueue(in string clientId, in string resourceId);
};


typedef sequence<string> StringSeq;
interface ClientIDListInterface {
    void addClientID(in string clientId);
    void removeClientID(in string clientId);
    StringSeq getClientIDs();
};