package ServerInterfacePackage;

/**
* ServerInterfacePackage/ResourceExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Friday, January 3, 2025 3:40:24 PM CET
*/

public final class ResourceExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerInterfacePackage.ResourceException value = null;

  public ResourceExceptionHolder ()
  {
  }

  public ResourceExceptionHolder (ServerInterfacePackage.ResourceException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerInterfacePackage.ResourceExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerInterfacePackage.ResourceExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerInterfacePackage.ResourceExceptionHelper.type ();
  }

}
